[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
ignore = []
[licenses]
unlicensed = "deny"
allow = [
    "MIT",
]
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"
[bans]
multiple-versions = "warn"
wildcards = "deny"
[sources]
unknown-registry = "deny"
unknown-git = "deny"
