[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
ignore = [
    # `clap 2.33` is not affected by this.
    "RUSTSEC-2018-0006",
    # No safe upgrade is available
    "RUSTSEC-2020-0016",
]
[licenses]
unlicensed = "deny"
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "BSL-1.0",
    "CC0-1.0",
    "ISC",
    "MIT",
]
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"
[bans]
multiple-versions = "warn"
wildcards = "deny"
[sources]
unknown-registry = "deny"
unknown-git = "deny"
