name: CI
on:
  push:
    branches: [ master, develop ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ master ]
defaults:
  run:
    shell: bash
env:
  PROJECT_NAME: ckb-dev
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -F warnings
  RUST_BACKTRACE: full
  RUST_TOOLCHAIN: 1.54.0
jobs:
  rustfmt:
    name: Checks / Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  clippy:
    name: Checks / Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true
          components: clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --locked -- --deny warnings
  cargo-deny:
    name: Checks / Deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Cache Key
        id: cache-key
        run: echo "::set-output name=yyyymm::$(/bin/date -u "+%Y%m")"
      - uses: actions/cache@v2
        id: cache-cargo-deny
        with:
          path: ~/.cargo/bin/cargo-deny
          key: ${{ runner.os }}-cargo-deny-${{ steps.cache-key.outputs.yyyymm }}
      - name: Setup
        if: steps.cache-cargo-deny.outputs.cache-hit != 'true'
        run: cargo deny --version || cargo install cargo-deny --locked
      - uses: actions-rs/cargo@v1
        with:
          command: deny
          args: check --hide-inclusion-graph --show-stats
  test:
    name: Tests / Build & Test
    needs: [ rustfmt, clippy ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [ stable ]
        os: [ ubuntu-18.04, ubuntu-20.04 ]
        include:
          - rust: 1.51.0 # MSRV
            os: ubuntu-latest
      fail-fast: true
      max-parallel: 3
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --all
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --all
  success:
    name: Success
    if: ${{ success() }}
    needs: [ cargo-deny, test ]
    runs-on: ubuntu-latest
    steps:
      - name: Succeed
        run: exit 0
  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: [ success ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04 ]
      fail-fast: true
      max-parallel: 2
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --verbose --all
      - name: Package
        id: package
        run: |
          set -euo pipefail
          version="$(git describe --first-parent --tags --always --dirty --abbrev=7)"
          raw_name="${PROJECT_NAME}-$(uname -o)-$(uname -m)-$(lsb_release -si)-$(lsb_release -sc)-${version}"
          fullname="$(echo "${raw_name}" | tr '[\\/ ]' '_' | tr '[:upper:]' '[:lower:]')"
          mkdir "${fullname}"
          cp LICENSE target/release/ckb-dev "${fullname}"/
          tar czvf "${fullname}.tar.gz" "${fullname}"
          echo "::set-output name=file_path::${fullname}.tar.gz"
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: ${{ steps.package.outputs.file_path }}
      - uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          dry-run: true
