name: CI
on:
  push:
    branches: [ master, develop ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ master ]
defaults:
  run:
    shell: bash
env:
  PROJECT_NAME: ckb-dev
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -F warnings
  RUST_BACKTRACE: full
  RUST_TOOLCHAIN: 1.54.0
jobs:
  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04 ]
      fail-fast: true
      max-parallel: 2
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --verbose --all
      - name: Package
        id: package
        run: |
          set -euo pipefail
          version="$(git describe --first-parent --tags --always --dirty --abbrev=7)"
          raw_name="${PROJECT_NAME}-$(uname -o)-$(uname -m)-$(lsb_release -si)-$(lsb_release -sc)-${version}"
          fullname="$(echo "${raw_name}" | tr '[\\/ ]' '_' | tr '[:upper:]' '[:lower:]')"
          mkdir "${fullname}"
          cp LICENSE target/release/ckb-dev "${fullname}"/
          tar czvf "${fullname}.tar.gz" "${fullname}"
          echo "::set-output name=file_path::${fullname}.tar.gz"
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: ${{ steps.package.outputs.file_path }}
      - uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          dry-run: true
